### ISSUE TITLE
about DF-GED algorithm 

### ISSUE THREAD

**Issue by gongxq19** [ziqi92/Modof#2]
Dear sir,
  Hi, I don’t know how to extract pairs of molecules with a single disconnection site, is it convenient to share the code of the DF-GED algorithm? I would be very grateful if you can help me.
  Best Regards for you!

**Comment by ziqi92** [comment]
Hi,

We simply use the function "optimal_edit_paths" provided by Networkx to compute the distance between two graphs.  You can take a look at this file [link](https://github.com/ziqi92/Modof/blob/main/data_preprocessing/transfer.py) for the details. As for extracting pairs of molecules, you can directly use the command below to process your data.

`python ./data_preprocessing/preprocess.py --train train_file_name –-output out_file_name –-batch_size NNN --batch_id ZZZ `

 Please let me know if you have any other questions. 

Best,
Ziqi

**Comment by gongxq19** [comment]
Dear ziqi,

I would like to ask another question. When I used my own data, the tensors-*.pkl file was not generated after processing the data. I think it may be the problem of the file format. Now I have over 10,000 molecules. How can I process my file into train_file.txt format?
Thank you very much for your answer.

Sincerely,
xiaoqing

**Comment by ziqi92** [comment]
Hi Xiaoqing,

I uploaded my scripts used to get molecule pairs to another repository https://github.com/ninglab/Modof/tree/main/data_preprocessing. To use the model, you have to have similar molecule pairs first. Please take a look at the file "get_similarity.py". 

Best,
Ziqi

**Comment by gongxq19** [comment]
Hi Ziqi,

Thanks for your patience, I would like to ask a question about pair_with_prop.pkl. How to get pair_with_prop.pkl file in get_data.py script? I can't find the pair_with_prop.pkl.

Sincerely,
Xiaoqing

**Comment by ziqi92** [comment]
Hi Xiaoqing,

The "pair_with_prop.pkl" file simply includes similar molecule pairs and their property values. I didn't upload the "pair_with_prop.pkl" file since the size of this file is too large.

You can directly calculate the property values of all the molecules in the similar molecule pairs, and then select those pairs which satisfy the property constraint (one has a significantly better property value than another one).

Best,
Ziqi
