### ISSUE TITLE
backward issue

### ISSUE THREAD

**Issue by XIXIYOUNG2018** [ziqi92/Modof#3]
when i train modof, , a problem occur in backward () function.
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [860, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later
 Is there any suggestion in fix this problem?

**Comment by ziqi92** [comment]
Thank you for your interest!

Can you provide more information like the script and dataset you used to run modof, and also your environment?
